#!/usr/bin/env python3
"""
Migration 054: Fix gig_worker / application / worker_rate_audit permissions
             and add ON DELETE SET NULL to specialization FK constraints.

ROOT CAUSE OF BUG
-----------------
Deleting a WorkerSpecialization record raises:
    psycopg2.errors.InsufficientPrivilege: permission denied for table gig_worker

SQLAlchemy's ORM issues a SELECT on gig_worker (and application, worker_rate_audit)
to NULL-out their specialization_id columns before it fires the DELETE.  If the
application database user lacks SELECT / UPDATE privilege on those tables the
whole operation fails.

This migration fixes the issue two ways:

  1. GRANTS SELECT, INSERT, UPDATE, DELETE on gig_worker and application to the
     application DB user (worker_rate_audit is covered by migration 051).

  2. Drops and recreates the three FK constraints that reference
     worker_specialization with ON DELETE SET NULL, so that PostgreSQL handles
     the NULL-out at the database level.  The companion ORM change
     (passive_deletes=True on the backrefs) tells SQLAlchemy to skip its own
     SELECT+UPDATE and rely on the database instead.

Usage
-----
  # Normal (app user must own or have privileges to alter the tables):
  python migrations/054_fix_gig_worker_specialization_permissions.py

  # If app user is not a superuser / table owner, supply a superuser URL:
  SUPERUSER_DATABASE_URL="postgresql://postgres:secret@host/db" \\
  python migrations/054_fix_gig_worker_specialization_permissions.py
"""

import os
import sys
from urllib.parse import urlparse

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from sqlalchemy import create_engine, text


def get_db_username(url):
    return urlparse(url).username or ''


def normalise_url(url):
    if url.startswith('postgres://'):
        return url.replace('postgres://', 'postgresql://', 1)
    return url


def run_migration():
    database_url = os.environ.get('DATABASE_URL', '')
    superuser_url = os.environ.get('SUPERUSER_DATABASE_URL', '') or database_url

    if not database_url:
        print("ERROR: DATABASE_URL environment variable is not set.")
        return False

    is_postgres = 'postgresql' in database_url or 'postgres' in database_url

    print("=" * 65)
    print("Migration 054: Fix gig_worker/application specialization FK perms")
    print("=" * 65)

    if not is_postgres:
        print("Database type: SQLite")
        print("SQLite does not use role-based permissions – no action needed.")
        return True

    app_user = get_db_username(database_url)
    if not app_user:
        print("ERROR: Could not extract username from DATABASE_URL.")
        return False

    grant_url = normalise_url(superuser_url)
    grant_user = get_db_username(grant_url)

    print(f"Database type      : PostgreSQL")
    print(f"Application DB user: {app_user}")
    if grant_user and grant_user != app_user:
        print(f"Granting via       : {grant_user} (superuser URL)")
    print()

    engine = create_engine(grant_url)

    # ------------------------------------------------------------------
    # Step 1: Grant DML privileges on gig_worker and application tables
    # ------------------------------------------------------------------
    grant_statements = [
        f'GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE gig_worker TO "{app_user}"',
        f'GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE application TO "{app_user}"',
    ]

    # ------------------------------------------------------------------
    # Step 2: Recreate the three FK constraints with ON DELETE SET NULL
    #
    # Standard constraint names generated by PostgreSQL / SQLAlchemy:
    #   gig_worker.specialization_id   -> gig_worker_specialization_id_fkey
    #   application.specialization_id  -> application_specialization_id_fkey
    #   worker_rate_audit.specialization_id -> worker_rate_audit_specialization_id_fkey
    # ------------------------------------------------------------------
    fk_statements = [
        # gig_worker
        'ALTER TABLE gig_worker DROP CONSTRAINT IF EXISTS gig_worker_specialization_id_fkey',
        ('ALTER TABLE gig_worker ADD CONSTRAINT gig_worker_specialization_id_fkey '
         'FOREIGN KEY (specialization_id) REFERENCES worker_specialization(id) ON DELETE SET NULL'),

        # application
        'ALTER TABLE application DROP CONSTRAINT IF EXISTS application_specialization_id_fkey',
        ('ALTER TABLE application ADD CONSTRAINT application_specialization_id_fkey '
         'FOREIGN KEY (specialization_id) REFERENCES worker_specialization(id) ON DELETE SET NULL'),

        # worker_rate_audit
        'ALTER TABLE worker_rate_audit DROP CONSTRAINT IF EXISTS worker_rate_audit_specialization_id_fkey',
        ('ALTER TABLE worker_rate_audit ADD CONSTRAINT worker_rate_audit_specialization_id_fkey '
         'FOREIGN KEY (specialization_id) REFERENCES worker_specialization(id) ON DELETE SET NULL'),
    ]

    all_statements = grant_statements + fk_statements

    success_count = 0
    skip_count = 0
    error_count = 0

    with engine.connect() as conn:
        for stmt in all_statements:
            try:
                conn.execute(text(stmt))
                conn.commit()
                success_count += 1
                print(f"[OK]   {stmt}")
            except Exception as e:
                err = str(e).lower()
                if 'already' in err and 'privilege' in err:
                    skip_count += 1
                    print(f"[SKIP] {stmt}")
                    print(f"       (privilege already granted)")
                    conn.rollback()
                elif 'does not exist' in err and 'constraint' not in err:
                    skip_count += 1
                    print(f"[SKIP] {stmt}")
                    print(f"       (object does not exist)")
                    conn.rollback()
                else:
                    error_count += 1
                    print(f"[ERROR] {stmt}")
                    print(f"        {e}")
                    conn.rollback()

    print()
    print("=" * 65)
    print("Migration 054 Summary")
    print("=" * 65)
    print(f"Successful : {success_count}")
    print(f"Skipped    : {skip_count}")
    print(f"Errors     : {error_count}")
    print()

    if error_count > 0:
        print("Migration completed with errors.")
        print()
        print("The statements failed because the connecting user is not the")
        print("table owner / superuser.  Retry with a superuser connection:")
        print()
        print("  SUPERUSER_DATABASE_URL='postgresql://postgres:secret@host/db' \\")
        print("  python migrations/054_fix_gig_worker_specialization_permissions.py")
        print()
        print("Or run these in psql as a superuser:")
        print()
        print(f'  GRANT SELECT, INSERT, UPDATE, DELETE ON gig_worker TO "{app_user}";')
        print(f'  GRANT SELECT, INSERT, UPDATE, DELETE ON application TO "{app_user}";')
        print()
        print('  ALTER TABLE gig_worker DROP CONSTRAINT IF EXISTS gig_worker_specialization_id_fkey;')
        print('  ALTER TABLE gig_worker ADD CONSTRAINT gig_worker_specialization_id_fkey')
        print('    FOREIGN KEY (specialization_id) REFERENCES worker_specialization(id) ON DELETE SET NULL;')
        print()
        print('  ALTER TABLE application DROP CONSTRAINT IF EXISTS application_specialization_id_fkey;')
        print('  ALTER TABLE application ADD CONSTRAINT application_specialization_id_fkey')
        print('    FOREIGN KEY (specialization_id) REFERENCES worker_specialization(id) ON DELETE SET NULL;')
        print()
        print('  ALTER TABLE worker_rate_audit DROP CONSTRAINT IF EXISTS worker_rate_audit_specialization_id_fkey;')
        print('  ALTER TABLE worker_rate_audit ADD CONSTRAINT worker_rate_audit_specialization_id_fkey')
        print('    FOREIGN KEY (specialization_id) REFERENCES worker_specialization(id) ON DELETE SET NULL;')
        return False

    print("Migration 054 completed successfully.")
    return True


if __name__ == '__main__':
    success = run_migration()
    sys.exit(0 if success else 1)
